### ISSUE TITLE
sticky year picker is running into sticky navbar

### ISSUE THREAD

**Issue by fgregg** [datamade/bga-payroll#567] opened 2021-11-16 14:59 UTC
When you scrolldown the the sticky year picker collides with the sticky navbar.
![Screenshot 2021-11-16 at 09-58-11 Cook County SD 130](https://user-images.githubusercontent.com/536941/142009080-063cc83b-d306-4218-87fc-e1e2199c176e.png)

Let's always have the year picker always below the navbar.

**Comment by hancush** [comment] 2021-11-16 15:03
Dupe of #531, will let you decide which to keep, @fgregg 🙃

**Closed** 2021-11-16 15:07 UTC
