### ISSUE TITLE
Missing employees

### ISSUE THREAD

**Issue by fgregg** [datamade/bga-payroll#558] opened 2021-11-03 01:38 UTC
On the [Wauconda Library District page](https://salary.bettergov.org/department/wauconda-library-district-information-services-ec8b3770/), it says there are 26 employees

<img width="817" alt="Screen Shot 2021-11-02 at 9 37 29 PM" src="https://user-images.githubusercontent.com/536941/139999066-f203468c-c244-4821-bb91-65d609491ede.png">

But when you click through to see all 26, there are only 2 listed:

https://salary.bettergov.org/search/?entity_type=person&employer=wauconda-library-district-information-services-ec8b3770&year=2018
<img width="1238" alt="Screen Shot 2021-11-02 at 9 38 27 PM" src="https://user-images.githubusercontent.com/536941/139999128-989b7f7f-2eb8-4a7c-aae8-bb1afb5c812a.png">

**Comment by hancush** [comment] 2021-11-03 12:54
Dupe of https://github.com/datamade/bga-payroll/issues/539. This was addressed on staging and will be fixed on the live site when we deploy the new data.

![Screen Shot 2021-11-03 at 7 54 02 AM](https://user-images.githubusercontent.com/12176173/140063604-ff69584c-9225-4d0d-9814-21d044f59c5e.png)
![screencapture-bga-payroll-datamade-us-search-2021-11-03-07_54_10](https://user-images.githubusercontent.com/12176173/140063626-f4068e5e-49ad-4297-ba41-80048d20644e.png)

**Closed** 2021-11-03 13:03 UTC
